version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_AI_API_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AI_SERVICE_URL=http://ai-service:5000
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app
      - ./ai/data:/app/data
      - ./ai/models:/app/models
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  redis_data: